services:
  db:
    image: mysql:8
    restart: always
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: '@#4!A^@*VA9'
    volumes:
      - ./api-and-cli-client/src/server/data/schema.sql:/docker-entrypoint-initdb.d/init.sql:ro
